/**
 * Centralized icon exports from Ant Design Icons.
 *
 * @description
 * Re-exports commonly used Ant Design icons with a consistent naming convention.
 * All icons are prefixed with "Icon" for easy identification and autocomplete.
 *
 * @remarks
 * - Icons are imported from @ant-design/icons and tree-shaken
 * - Use these exports instead of importing directly from @ant-design/icons
 * - Naming pattern: Icon + IconName from Ant Design
 */
export {
    AlignCenterOutlined as IconAlignCenterOutlined,
    AlignLeftOutlined as IconAlignLeftOutlined,
    AlignRightOutlined as IconAlignRightOutlined,
    AndroidFilled as IconAndroidFilled,
    ApiOutlined as IconApiOutlined,
    AppleFilled as IconAppleFilled,
    AppstoreOutlined as IconAppstoreOutlined,
    ArrowLeftOutlined as IconArrowLeftOutlined,
    ArrowRightOutlined as IconArrowRightOutlined,
    BellFilled as IconBellFilled,
    BellOutlined as IconBellOutlined,
    BoldOutlined as IconBoldOutlined,
    BulbFilled as IconBulbFilled,
    CalendarOutlined as IconCalendarOutlined,
    CameraOutlined as IconCameraOutlined,
    CaretDownOutlined as IconCaretDownOutlined,
    CaretLeftOutlined as IconCaretLeftOutlined,
    CaretRightFilled as IconCaretRightFilled,
    CaretRightOutlined as IconCaretRightOutlined,
    CarOutlined as IconCarOutlined,
    CheckCircleFilled as IconCheckCircleFilled,
    CheckCircleOutlined as IconCheckCircleOutlined,
    ClockCircleOutlined as IconClockCircleOutlined,
    CloseCircleFilled as IconCloseCircleFilled,
    CloseCircleOutlined as IconCloseCircleOutlined,
    CloseSquareOutlined as IconCloseSquareOutlined,
    CodeOutlined as IconCodeOutlined,
    CommentOutlined as IconCommentOutlined,
    CreditCardOutlined as IconCreditCardOutlined,
    DeleteFilled as IconDeleteFilled,
    DesktopOutlined as IconDesktopOutlined,
    DollarOutlined as IconDollarOutlined,
    DownOutlined as IconDownOutlined,
    EditFilled as IconEditFilled,
    EditOutlined as IconEditOutlined,
    EllipsisOutlined as IconEllipsisOutlined,
    EnvironmentOutlined as IconEnvironmentOutlined,
    ExclamationCircleOutlined as IconExclamationCircleOutlined,
    FacebookFilled as IconFacebookFilled,
    FilePdfOutlined as IconFilePdfOutlined,
    FileSearchOutlined as IconFileSearchOutlined,
    FileTextOutlined as IconFileTextOutlined,
    FilterOutlined as IconFilterOutlined,
    FireFilled as IconFireFilled,
    FolderOutlined as IconFolderOutlined,
    GoogleOutlined as IconGoogleOutlined,
    GroupOutlined as IconGroupOutlined,
    HeartFilled as IconHeartFilled,
    HeartOutlined as IconHeartOutlined,
    HomeFilled as IconHomeFilled,
    HomeOutlined as IconHomeOutlined,
    InboxOutlined as IconInboxOutlined,
    InstagramFilled as IconInstagramFilled,
    ItalicOutlined as IconItalicOutlined,
    LikeFilled as IconLikeFilled,
    LikeOutlined as IconLikeOutlined,
    LinkOutlined as IconLinkOutlined,
    LoadingOutlined as IconLoadingOutlined,
    LockOutlined as IconLockOutlined,
    LoginOutlined as IconLoginOutlined,
    LogoutOutlined as IconLogoutOutlined,
    MailOutlined as IconMailOutlined,
    MenuOutlined as IconMenuOutlined,
    MenuUnfoldOutlined as IconMenuUnfoldOutlined,
    MobileOutlined as IconMobileOutlined,
    NotificationOutlined as IconNotificationOutlined,
    OrderedListOutlined as IconOrderedListOutlined,
    PictureOutlined as IconPictureOutlined,
    PlayCircleTwoTone as IconPlayCircleTwoTone,
    PlaySquareOutlined as IconPlaySquareOutlined,
    PlusOutlined as IconPlusOutlined,
    QuestionCircleOutlined as IconQuestionCircleOutlined,
    ReadOutlined as IconReadOutlined,
    SafetyOutlined as IconSafetyOutlined,
    SaveOutlined as IconSaveOutlined,
    SearchOutlined as IconSearchOutlined,
    SettingOutlined as IconSettingOutlined,
    ShareAltOutlined as IconShareAltOutlined,
    ShopOutlined as IconShopOutlined,
    ShoppingOutlined as IconShoppingOutlined,
    SoundOutlined as IconSoundOutlined,
    StarFilled as IconStarFilled,
    StarOutlined as IconStarOutlined,
    StrikethroughOutlined as IconStrikethroughOutlined,
    SyncOutlined as IconSyncOutlined,
    TabletOutlined as IconTabletOutlined,
    TagOutlined as IconTagOutlined,
    TeamOutlined as IconTeamOutlined,
    TwitterOutlined as IconTwitterOutlined,
    UnderlineOutlined as IconUnderlineOutlined,
    UnlockOutlined as IconUnlockOutlined,
    UnorderedListOutlined as IconUnorderedListOutlined,
    UserAddOutlined as IconUserAddOutlined,
    UserOutlined as IconUserOutlined,
    VideoCameraFilled as IconVideoCameraFilled,
    WhatsAppOutlined as IconWhatsAppOutlined,
    YoutubeFilled as IconYoutubeFilled
} from "@ant-design/icons";
