/**
 * Centralized icon exports from Ant Design Icons.
 *
 * @description
 * Re-exports commonly used Ant Design icons with a consistent naming convention.
 * All icons are prefixed with "Icon" for easy identification and autocomplete.
 *
 * @remarks
 * - Icons are imported from @ant-design/icons and tree-shaken
 * - Use these exports instead of importing directly from @ant-design/icons
 * - Naming pattern: Icon + IconName from Ant Design
 */
export {
    AndroidFilled as IconAndroidFilled,
    ApiOutlined as IconApiOutlined,
    AppleFilled as IconAppleFilled,
    ArrowLeftOutlined as IconArrowLeftOutlined,
    ArrowRightOutlined as IconArrowRightOutlined,
    BellFilled as IconBellFilled,
    BellOutlined as IconBellOutlined,
    BulbFilled as IconBulbFilled,
    CameraOutlined as IconCameraOutlined,
    CaretDownOutlined as IconCaretDownOutlined,
    CaretLeftOutlined as IconCaretLeftOutlined,
    CaretRightFilled as IconCaretRightFilled,
    CaretRightOutlined as IconCaretRightOutlined,
    CarOutlined as IconCarOutlined,
    ClockCircleOutlined as IconClockCircleOutlined,
    CloseCircleFilled as IconCloseCircleFilled,
    CloseCircleOutlined as IconCloseCircleOutlined,
    CloseSquareOutlined as IconCloseSquareOutlined,
    CommentOutlined as IconCommentOutlined,
    DeleteFilled as IconDeleteFilled,
    DesktopOutlined as IconDesktopOutlined,
    DownOutlined as IconDownOutlined,
    EditFilled as IconEditFilled,
    EditOutlined as IconEditOutlined,
    EllipsisOutlined as IconEllipsisOutlined,
    EnvironmentOutlined as IconEnvironmentOutlined,
    ExclamationCircleOutlined as IconExclamationCircleOutlined,
    FacebookFilled as IconFacebookFilled,
    FileSearchOutlined as IconFileSearchOutlined,
    FileTextOutlined as IconFileTextOutlined,
    FilterOutlined as IconFilterOutlined,
    FireFilled as IconFireFilled,
    GoogleOutlined as IconGoogleOutlined,
    HeartFilled as IconHeartFilled,
    HeartOutlined as IconHeartOutlined,
    HomeFilled as IconHomeFilled,
    HomeOutlined as IconHomeOutlined,
    InstagramFilled as IconInstagramFilled,
    LikeFilled as IconLikeFilled,
    LikeOutlined as IconLikeOutlined,
    LoadingOutlined as IconLoadingOutlined,
    LockOutlined as IconLockOutlined,
    LoginOutlined as IconLoginOutlined,
    LogoutOutlined as IconLogoutOutlined,
    MailOutlined as IconMailOutlined,
    MenuOutlined as IconMenuOutlined,
    MenuUnfoldOutlined as IconMenuUnfoldOutlined,
    MobileOutlined as IconMobileOutlined,
    PlayCircleTwoTone as IconPlayCircleTwoTone,
    PlusOutlined as IconPlusOutlined,
    QuestionCircleOutlined as IconQuestionCircleOutlined,
    SafetyOutlined as IconSafetyOutlined,
    SaveOutlined as IconSaveOutlined,
    SearchOutlined as IconSearchOutlined,
    SettingOutlined as IconSettingOutlined,
    ShareAltOutlined as IconShareAltOutlined,
    StarFilled as IconStarFilled,
    StarOutlined as IconStarOutlined,
    SyncOutlined as IconSyncOutlined,
    TabletOutlined as IconTabletOutlined,
    TwitterOutlined as IconTwitterOutlined,
    UnlockOutlined as IconUnlockOutlined,
    UserAddOutlined as IconUserAddOutlined,
    UserOutlined as IconUserOutlined,
    VideoCameraFilled as IconVideoCameraFilled,
    WhatsAppOutlined as IconWhatsAppOutlined,
    YoutubeFilled as IconYoutubeFilled
} from "@ant-design/icons";
