import type { FormInstance } from "antd";
import { Form, Input } from "antd";
import type { FC } from "react";
import { TagsValidator } from "@/modules/lookup/presentation/utils/validators/lookup.tags.validator";
import type { Failure } from "@/shared/domain/failures/failure";
import type { FormContext } from "@/shared/domain/types/pagination";
import ErrorAlert from "@/shared/presentation/ui/ErrorAlert";

const { Item } = Form;

/**
 * Props for the TagForm component.
 *
 * @interface ITagFormProps
 * @property {FormInstance} form - Ant Design form instance
 * @property {Failure | null | undefined} error - API error to display
 * @property {FormContext} formContext - "CREATE" mode only (tags cannot be edited)
 */
interface ITagFormProps {
    form: FormInstance;
    error: Failure | null | undefined;
    formContext: FormContext;
}

/**
 * Form for creating tags.
 *
 * @component
 *
 * @description
 * Renders a name field with client-side validation matching the
 * backend constraints. The slug is auto-generated by the backend,
 * so only the name field is exposed. Displays API errors via
 * `ErrorAlert`.
 *
 * @param {ITagFormProps} props - Component props
 * @returns {JSX.Element} The tag form
 */
const TagForm: FC<ITagFormProps> = ({ form, error }) => {
    return (
        <Form
            form={form}
            size="large"
            layout="vertical"
            name="tag_form"
            validateTrigger={["onSubmit", "onBlur"]}
        >
            <ErrorAlert error={error} showIcon closable banner={false} />

            <Item name="name" label="Nom" rules={TagsValidator.name("Nom")}>
                <Input maxLength={50} placeholder="Nom du tag" />
            </Item>

            <Item name="slug" label="Slug" rules={TagsValidator.slug("Slug")}>
                <Input maxLength={50} placeholder="slug-du-tag" />
            </Item>
        </Form>
    );
};

export default TagForm;
